version: "2"

services:

### mysql
    mysql:
        image: mysql:5.6
        container_name:
            docker_mysql_1
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_DATABASE: "test"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "123456"
        volumes:
            - ./aliases.sh:/root/.bashrc
            - ~/wwwdata/mysql:/var/lib/mysql

## mongo
    mongo:
        image: mongo:3.6-stretch
        container_name:
            docker_mongo_1
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "123456"
        volumes:
            - ./aliases.sh:/root/.bashrc
            - ~/wwwdata/mongo/db:/data/db
            - ~/wwwdata/mongo/configdb:/data/configdb

### mongo-express
#    mongo-express:
#        image: mongo-express:latest
#        container_name:
#            docker_mongo-express_1
#        ports:
#            - "8081:8081"
#        environment:
#            ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
#            ME_CONFIG_MONGODB_ADMINPASSWORD: "123456"
#        volumes:
#            - ./aliases.sh:/root/.bashrc
#        restart: always

### redis
    redis:
        image: redis:alpine
        container_name:
            docker_redis_1
        ports:
            - "6379:6379"
        volumes:
            - ./aliases.sh:/etc/profile.d/aliases.sh
            - ./redis/redis.conf:/etc/redis/redis.conf
            - ~/wwwdata/redis:/data
        command: redis-server --requirepass 123456

### rabbitmq
    rabbitmq:
        image: rabbitmq:management-alpine
        container_name:
            docker_rabbitmq_1
        ports:
            - "15672:15672"
        volumes:
            - ./aliases.sh:/etc/profile.d/aliases.sh
            - ~/wwwdata/rabbitmq:/var/lib/rabbitmq
            - ~/wwwlogs/rabbitmq:/var/log/rabbitmq/log

### elasticsearch
    elasticsearch:
        image: elasticsearch:5-alpine
        container_name:
            docker_elastic_1
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            http.host: 0.0.0.0
            transport.host: 0.0.0.0
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        volumes:
            - ./aliases.sh:/etc/profile.d/aliases.sh
            - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ~/wwwdata/elasticsearch:/usr/share/elasticsearch/data
            - ~/wwwlogs/elasticsearch:/usr/share/elasticsearch/logs

### elasticsearch-head
#    elasticsearch-head:
#        image: mobz/elasticsearch-head:5-alpine
#        container_name:
#            docker_elastic-head_1
#        volumes:
#            - ./aliases.sh:/etc/profile.d/aliases.sh
#        ports:
#        - "9100:9100"

### zookeeper
    zookeeper:
        image: zookeeper
        container_name:
          docker_zookeeper_1
        ports:
            - "2181:2181"
### kafka
    kafka:
        image: wurstmeister/kafka
        container_name:
            docker_kafka_1
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - zookeeper

## hbase
    hbase:
        image: dajobe/hbase
        container_name:
            docker_hbase_1
        ports:
            - "16001:8080"
            - "16002:9090"
            - "16010:16010"
        volumes:
            - ~/wwwdata/hbase:/data

### etcd
#    etcd:
#        image: bitnami/etcd:3
#        container_name:
#            docker_etcd_1
#        ports:
#            - "2379:2379"
#            - "2380:2380"
#        environment:
#            - ALLOW_NONE_AUTHENTICATION=yes

### php5-fpm
    php5-fpm:
        image: raw34/php5-fpm
        # build: ./php/php5
        # image: php:5.6-fpm
        container_name:
            docker_php5-fpm_1
        environment:
            MOLTEN_ENABLE: 0
            MOLTEN_TRACING_CLI: 0
            MOLTEN_SPAN_VERSION: v1
            MOLTEN_SPAN_FORMAT: zipkin
            MOLTEN_SINK_TYPE: 1
            MOLTEN_SINK_HOST: zipkin
        volumes:
            - ./aliases.sh:/etc/profile.d/aliases.sh
            - ./php/php5.ini:/usr/local/etc/php/php.ini
            - ./php/php5-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
            - ~/wwwlogs/php:/var/log/php
            - ~/wwwroot/repo:/www
            - ~/data:/alidata
            - ~/.composer/cache:/root/.composer/cache
            - ~/.ssh:/root/.ssh
        links:
            - mysql
            - mongo
            - redis
            - kafka
            - rabbitmq
            - elasticsearch
        extra_hosts:
            - "php5-localhost.docker:172.17.0.1"
            - "php7-localhost.docker:172.17.0.1"

### php7-fpm
    php7-fpm:
        image: raw34/php7.1-fpm
#        image: raw34/php7-fpm
#        image: raw34/php7-fpm-stretch
        # build: ./php/php7
        # image: php:fpm
        container_name:
            docker_php7-fpm_1
        environment:
            MOLTEN_ENABLE: 0
            MOLTEN_TRACING_CLI: 0
            MOLTEN_SPAN_VERSION: v1
            MOLTEN_SPAN_FORMAT: zipkin
            MOLTEN_SINK_TYPE: 1
            MOLTEN_SINK_HOST: zipkin
        volumes:
            - ./aliases.sh:/etc/profile.d/aliases.sh
            - ./php/php7.ini:/usr/local/etc/php/php.ini
            - ./php/php7-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
            - ~/wwwlogs/php:/var/log/php
            - ~/wwwroot/repo:/www
            - ~/data:/alidata
            - ~/.composer/cache:/root/.composer/cache
            - ~/.ssh:/root/.ssh
        links:
            - mysql
            - mongo
            - redis
            - kafka
            - rabbitmq
            - elasticsearch
        extra_hosts:
            - "php5-localhost.docker:172.17.0.1"
            - "php7-localhost.docker:172.17.0.1"
#        ulimits:
#          nproc: 65535
#          nofile:
#            soft: 20000
#            hard: 40000

### nginx
    nginx:
        image: nginx:alpine
        container_name:
            docker_nginx_1
        ports:
            - "80:80"
            - "433:433"
        volumes:
            - ./aliases.sh:/etc/profile.d/aliases.sh
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/php5-localhost.conf:/etc/nginx/sites-available/php5-localhost.conf
            - ./nginx/php7-localhost.conf:/etc/nginx/sites-available/php7-localhost.conf
            - ./nginx/php5-xhgui.conf:/etc/nginx/sites-available/php5-xhgui.conf
            - ./nginx/php7-xhgui.conf:/etc/nginx/sites-available/php7-xhgui.conf
            - ~/wwwetc/nginx/sites-available:/etc/nginx/sites-available
            - ~/wwwlogs/nginx:/var/log/nginx
        volumes_from:
            - php5-fpm
            - php7-fpm
        links:
            - php5-fpm
            - php7-fpm
