version: "2"

services:

### mysql
    mysql:
        image: mysql:5.6
        container_name:
            docker_mysql_1
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_DATABASE: "test"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "123456"
        volumes:
            - ~/wwwdata/mysql:/var/lib/mysql

### mongo
    mongo:
        image: mongo:3.6-stretch
        container_name:
            docker_mongo_1
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "123456"
        volumes:
            - ~/wwwdata/mongo/db:/data/db
            - ~/wwwdata/mongo/configdb:/data/configdb

### mongo-express
    mongo-express:
        image: mongo-express:latest
        container_name:
            docker_mongo-express_1
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
            ME_CONFIG_MONGODB_ADMINPASSWORD: "123456"
        restart: always

### redis
    redis:
        image: redis:alpine
        container_name:
            docker_redis_1
        volumes:
            - ~/wwwdata/redis:/data

### rabbitmq
    rabbitmq:
        image: rabbitmq:management-alpine
        container_name:
            docker_rabbitmq_1
        ports:
            - "15672:15672"
        volumes:
            - ~/wwwdata/rabbitmq:/var/lib/rabbitmq

### elasticsearch
    elasticsearch:
        image: elasticsearch:5-alpine
        container_name:
            docker_elastic_1
        ports:
            - "9200:9200"
        environment:
            http.host: 0.0.0.0
            transport.host: 0.0.0.0
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        volumes:
            - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ~/wwwdata/elasticsearch:/usr/share/elasticsearch/data
            - ~/wwwlogs/elasticsearch:/usr/share/elasticsearch/logs

### php5-fpm
    php5-fpm:
        # image: php:5.6-fpm
        # image: docker_php5-fpm
        build: ./php/php5
        container_name:
            docker_php5-fpm_1
        volumes:
            - ./php/php5/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
            - ~/wwwlogs/php:/var/log/php
            - ~/wwwroot/repo:/www
            - ~/.ssh:/root/.ssh
        links:
            - mysql
            - mongo
            - redis
            - rabbitmq
            - elasticsearch

### php7-fpm
    php7-fpm:
        # image: php:fpm
        # image: docker_php7-fpm
        build: ./php/php7
        container_name:
            docker_php7-fpm_1
        volumes:
            - ./php/php7/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
            - ~/wwwlogs/php:/var/log/php
            - ~/wwwroot/repo:/www
            - ~/.ssh:/root/.ssh
        links:
            - mysql
            - mongo
            - redis
            - rabbitmq
            - elasticsearch

### nginx
    nginx:
        image: nginx:alpine
        container_name:
            docker_nginx_1
        ports:
            - "80:80"
            - "433:433"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/php5-localhost.conf:/etc/nginx/sites-available/php5-localhost.conf
            - ./nginx/php7-localhost.conf:/etc/nginx/sites-available/php7-localhost.conf
            - ./nginx/php5-xhgui.conf:/etc/nginx/sites-available/php5-xhgui.conf
            - ./nginx/php7-xhgui.conf:/etc/nginx/sites-available/php7-xhgui.conf
            - ~/wwwetc/nginx/sites-available:/etc/nginx/sites-available
            - ~/wwwlogs/nginx:/var/log/nginx
        volumes_from:
            - php5-fpm
            - php7-fpm
        links:
            - php5-fpm
            - php7-fpm

#### golang
#    golang:
#        image: golang:alpine
#        container_name:
#            docker_golang_1
#        volumes:
#            - ~/wwwlogs/golang:/var/log/golang
#            - ~/wwwroot/repo/gopath:/go
#            - ~/.ssh:/root/.ssh
#        stdin_open: true
#        tty: true
#        command: /bin/ash
#
#### java-8
#    java-8:
#        image: java:8-alpine
#        container_name:
#            docker_java-8_1
#        stdin_open: true
#        tty: true
#        command: /bin/ash
#
#### tomcat-8
#    tomcat-8:
#        image: tomcat:8-alpine
#        container_name:
#            docker_tomcat-8_1
#        volumes:
#            - ~/.ssh:/root/.ssh
#
#### node
#    node:
#        image: node:alpine
#        container_name:
#            docker_node_1
#        stdin_open: true
#        tty: true
#        command: /bin/ash
